# try:
#     print(1/0)
# except ZeroDivisionError:
#     print("ZeroDivisionError")
# except Exception:
#     print("Exception")

def func(a=3):
    return a

print(func())